# Shim for backward compatibility - re-exports from src.verification.suite_builder
from src.verification.suite_builder import (
    AGENT_SUITE_MAP,
    CHECK_IMPLEMENTATIONS,
    FIQH_VERIFICATION_SUITE,
    HADITH_VERIFICATION_SUITE,
    TAFSIR_VERIFICATION_SUITE,
    AQEEDAH_VERIFICATION_SUITE,
    SEERAH_VERIFICATION_SUITE,
    USUL_FIQH_VERIFICATION_SUITE,
    HISTORY_VERIFICATION_SUITE,
    LANGUAGE_VERIFICATION_SUITE,
    build_verification_suite_for,
    create_suite_for_agent,
    get_check_implementation,
    list_available_suites,
    register_all_checks,
    register_check,
    run_verification_suite,
)

__all__ = [
    "AGENT_SUITE_MAP",
    "CHECK_IMPLEMENTATIONS",
    "FIQH_VERIFICATION_SUITE",
    "HADITH_VERIFICATION_SUITE",
    "TAFSIR_VERIFICATION_SUITE",
    "AQEEDAH_VERIFICATION_SUITE",
    "SEERAH_VERIFICATION_SUITE",
    "USUL_FIQH_VERIFICATION_SUITE",
    "HISTORY_VERIFICATION_SUITE",
    "LANGUAGE_VERIFICATION_SUITE",
    "build_verification_suite_for",
    "create_suite_for_agent",
    "get_check_implementation",
    "list_available_suites",
    "register_all_checks",
    "register_check",
    "run_verification_suite",
]
